### ISSUE TITLE
Microflow is never triggered

### ISSUE THREAD

**Issue by Pmarouga** [hunterkoppenclevr/tabAction#1]
When using the extension to open a link, everything works fine. If I choose call microflow however, the microflow is never triggered. I have a breakpoint on each step of the microflow but none is triggered. Any ideas why I get this behavior?

**Comment by Pmarouga** [comment]
Same with nanoflows, never triggered.

**Comment by hunter-koppen** [comment]
Hi @Pmarouga, I ran into the same problem a few days ago. Sometimes the can execute check returns false when it should return true so I have removed that check and updated the widget in the marketplace. Please try it again with the new version!

**Comment by Pmarouga** [comment]
![tabONCACT](https://user-images.githubusercontent.com/24904884/157200988-7d6abfb2-b42c-4b88-9a20-bb954d7b12e0.PNG)
v1.0.2 seems the latest version, with release date 1/20. Are you referring to that one?

**Comment by hunter-koppen** [comment]
It should be there now, takes a little while to update.

**Comment by Pmarouga** [comment]
v1.0.3 microflows are triggered. Thanks alot for the fast response!
